# Generated by Django 2.2.1 on 2020-06-20 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_model', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ordr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Article_num', models.CharField(max_length=200)),
                ('sizes', models.CharField(max_length=200)),
                ('delivery_location', models.CharField(max_length=200)),
                ('payment_mode', models.CharField(max_length=200)),
                ('email_id', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField()),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
    ]
