# Generated by Django 2.2.1 on 2020-06-30 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website_model', '0002_auto_20200620_1624'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile',
        ),
    ]
