# Generated by Django 2.2.1 on 2020-07-04 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_model', '0003_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordr',
            name='email_id',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
