# Generated by Django 2.2.1 on 2020-07-04 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_model', '0004_auto_20200704_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='Email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='ordr',
            name='email_id',
            field=models.EmailField(max_length=254),
        ),
    ]
