# Generated by Django 2.2.1 on 2020-07-07 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_model', '0006_auto_20200704_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='Email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='member',
            name='profile_pic',
            field=models.ImageField(upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='ordr',
            name='email_id',
            field=models.EmailField(max_length=254),
        ),
    ]
