# Generated by Django 2.2.1 on 2020-07-12 15:02

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('website_model', '0008_group'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='Grup',
        ),
    ]
