# Generated by Django 2.2.1 on 2020-07-12 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website_model', '0009_auto_20200712_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='ordr',
            name='email_id',
        ),
    ]
