# Generated by Django 2.2.1 on 2020-07-12 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website_model', '0011_auto_20200712_2046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordr',
            old_name='email_id',
            new_name='emai',
        ),
    ]
