# Generated by Django 2.2.1 on 2020-07-12 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website_model', '0012_auto_20200712_2047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordr',
            old_name='emai',
            new_name='email_id',
        ),
    ]
