# Generated by Django 2.2.1 on 2020-07-12 17:07

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('website_model', '0013_auto_20200712_2232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grup',
            old_name='users',
            new_name='Members',
        ),
    ]
