# Generated by Django 2.2.1 on 2020-07-13 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('website_model', '0014_auto_20200712_2237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Description', models.CharField(max_length=500)),
                ('profil_img', models.ImageField(upload_to='profile_pics')),
                ('Members', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website_model.Member')),
            ],
        )

    ]
