# Generated by Django 2.2.1 on 2020-07-13 04:10

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('website_model', '0015_auto_20200713_0929'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grup',
        ),
    ]
