# Generated by Django 2.2.1 on 2020-07-13 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website_model', '0016_delete_grup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='Members',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website_model.Member'),
        ),
    ]
