# Generated by Django 2.2.1 on 2020-07-13 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website_model', '0017_auto_20200713_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='Members',
        ),
        migrations.AddField(
            model_name='member',
            name='Groups',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website_model.Group'),
        ),
    ]
