# Generated by Django 2.2.1 on 2020-07-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_model', '0019_auto_20200714_1944'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Description', models.CharField(max_length=500)),
                ('profil_img', models.ImageField(upload_to='profile_pics')),
                ('Members', models.ManyToManyField(to='website_model.Member')),
            ],
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
